# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BatchVectorLayerSaver
                                 A QGIS plugin
 Saves all Layers in defined formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-21
        copyright            : (C) 2018 by Riccardo Klinger
        email                : riccardo.klinger@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BatchVectorLayerSaver class from file BatchVectorLayerSaver.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .batch_vector_layer_saver import BatchVectorLayerSaver
    return BatchVectorLayerSaver(iface)
